export class Section {
    amount: number;
    autoInvest: number;
    conDeadline: number;
    conDeadlineDay: number;
    conSn: string;
    countDownSecond: number;
    deadlineStr: string;
    enterId: number;
    escrowDirect: number;
    escrowFlag: number;
    f1: number;
    f8: number;
    flag: number;
    id: number;
    loanType: number;
    origiPtime: number;
    pid: number;
    raisedAmount: number;
    randNum: number;
    rate: number;
    refundType: number;
    reward: number;
    sectionType: number;
    sort: number;
    status: number;
    stime: number;
    transferReward: number;
}
